create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  external_id text not null,
  event text not null,
  status text,
  gross_amount bigint,
  currency text,
  payment_method text,
  customer_name text,
  customer_email text,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (external_id, event)
);

alter table public.payment_transactions enable row level security;

drop policy if exists "Admins can read payment transactions" on public.payment_transactions;
create policy "Admins can read payment transactions"
on public.payment_transactions
for select
to authenticated
using (public.is_campaign_admin());

revoke all on public.payment_transactions from anon;
grant select on public.payment_transactions to authenticated;
