create table if not exists public.lead_journey_events (
  id bigint generated by default as identity primary key,
  dedupe_key text not null unique,
  session_id uuid not null,
  stage text not null,
  request_id uuid,
  external_id text,
  donor_name text,
  donor_email text,
  amount bigint,
  currency text,
  city text,
  country_code text,
  latitude double precision,
  longitude double precision,
  ip_masked text,
  source text,
  device text,
  page_url text,
  occurred_at timestamptz not null default now(),
  constraint lead_journey_stage_check check (stage in ('offer', 'checkout', 'paid'))
);

create index if not exists lead_journey_events_occurred_idx
  on public.lead_journey_events (occurred_at desc);
create index if not exists lead_journey_events_session_idx
  on public.lead_journey_events (session_id, occurred_at);

alter table public.lead_journey_events enable row level security;

drop policy if exists "Admins can read lead journey events" on public.lead_journey_events;
create policy "Admins can read lead journey events"
on public.lead_journey_events
for select
to authenticated
using (public.is_campaign_admin());

revoke all on public.lead_journey_events from anon;
grant select on public.lead_journey_events to authenticated;

comment on table public.lead_journey_events is 'Real campaign, checkout and confirmed-payment milestones for the protected admin overview.';

insert into public.lead_journey_events (
  dedupe_key, session_id, stage, request_id, donor_name, donor_email, amount, currency,
  source, device, page_url, occurred_at
)
select
  'checkout:' || lead.request_id::text,
  lead.request_id,
  'checkout',
  lead.request_id,
  lead.donor_name,
  lead.email,
  lead.amount,
  lead.currency,
  case
    when coalesce(lead.tracking_context->>'ttclid', '') <> '' then 'TikTok Ads'
    when coalesce(lead.tracking_context->>'gclid', '') <> '' then 'Google Ads'
    when coalesce(lead.tracking_context->>'fbc', lead.tracking_context->>'fbp', '') <> '' then 'Meta Ads'
    else 'Direto / não identificado'
  end,
  lead.tracking_context->>'userAgent',
  lead.tracking_context->>'pageUrl',
  lead.created_at
from public.payment_leads lead
on conflict (dedupe_key) do nothing;

insert into public.lead_journey_events (
  dedupe_key, session_id, stage, external_id, donor_name, donor_email, amount, currency,
  source, device, page_url, occurred_at
)
select
  'paid:' || transaction.external_id,
  coalesce(matched_lead.request_id, gen_random_uuid()),
  'paid',
  transaction.external_id,
  coalesce(matched_lead.donor_name, transaction.customer_name),
  coalesce(matched_lead.email, transaction.customer_email),
  transaction.gross_amount,
  coalesce(transaction.currency, 'USD'),
  case
    when coalesce(matched_lead.tracking_context->>'ttclid', '') <> '' then 'TikTok Ads'
    when coalesce(matched_lead.tracking_context->>'gclid', '') <> '' then 'Google Ads'
    when coalesce(matched_lead.tracking_context->>'fbc', matched_lead.tracking_context->>'fbp', '') <> '' then 'Meta Ads'
    else 'Direto / não identificado'
  end,
  matched_lead.tracking_context->>'userAgent',
  matched_lead.tracking_context->>'pageUrl',
  transaction.occurred_at
from public.payment_transactions transaction
left join lateral (
  select lead.*
  from public.payment_leads lead
  where lower(lead.email) = lower(transaction.customer_email)
    and lead.amount = transaction.gross_amount
    and lead.currency = coalesce(transaction.currency, 'USD')
    and lead.created_at <= transaction.occurred_at
  order by lead.created_at desc
  limit 1
) matched_lead on true
where transaction.event = 'transaction.paid'
on conflict (dedupe_key) do nothing;
